### ISSUE TITLE
Add a copyright logo to all images

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/zirve#1]

**Comment by Keerti-Gautam** [comment]
Hi

Do you need a custom logo or the usual copyright logo would work?

**Comment by sakshamsaxena** [comment]
@Keerti-Gautam Hi! Thanks for taking this up :smile: 
I think a small custom logo would look great. Usual one would not be so cool I think.
Most welcome to initiate a PR! Looking forward to it :smile:

**Comment by Keerti-Gautam** [comment]
Hi @sakshamsaxena Thanks for the encouragement.
Can you explain me the design of the logo which you'd want?

**Comment by sakshamsaxena** [comment]
I think "Zirve" written in a fancy style would do. Something like Zangoora font?
